const data = [
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2001,
        position: 1,
        persantage: 20,
    },
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2005,
        position: 1,
        persantage: 25,
    },
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2015,
        position: 1,
        persantage: 22,
    },
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2024,
        position: 2,
        persantage: 20,
    },
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2023,
        position: 2,
        persantage: 20,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2001,
        position: 3,
        persantage: 10,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2005,
        position: 2,
        persantage: 15,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2015,
        position: 3,
        persantage: 20,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2024,
        position: 1,
        persantage: 30,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2023,
        position: 1,
        persantage: 30,
    },
    {
        name: 'C#',
        type: 'Object-Oriented',
        year: 2001,
        position: 4,
        persantage: 5,
    },
    {
        name: 'C#',
        type: 'Object-Oriented',
        year: 2005,
        position: 3,
        persantage: 7,
    },
    {
        name: 'C#',
        type: 'Object-Oriented',
        year: 2015,
        position: 4,
        persantage: 9,
    },
    {
        name: 'C#',
        type: 'Object-Oriented',
        year: 2024,
        position: 3,
        persantage: 10,
    },
    {
        name: 'C#',
        type: 'Object-Oriented',
        year: 2023,
        position: 3,
        persantage: 10,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2001,
        position: 5,
        persantage: 6,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2005,
        position: 4,
        persantage: 10,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2015,
        position: 2,
        persantage: 15,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2024,
        position: 2,
        persantage: 25,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2023,
        position: 2,
        persantage: 25,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2001,
        position: 2,
        persantage: 10,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2005,
        position: 5,
        persantage: 9,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2015,
        position: 5,
        persantage: 7,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2024,
        position: 4,
        persantage: 6,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2023,
        position: 4,
        persantage: 6,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2001,
        position: 6,
        persantage: 4,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2005,
        position: 6,
        persantage: 5,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2015,
        position: 8,
        persantage: 3,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2024,
        position: 6,
        persantage: 2,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2023,
        position: 6,
        persantage: 2,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2001,
        position: 3,
        persantage: 9,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2005,
        position: 2,
        persantage: 8,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2015,
        position: 5,
        persantage: 10,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2024,
        position: 5,
        persantage: 8,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2023,
        position: 5,
        persantage: 8,
    },
    {
        name: 'Swift',
        type: 'Multiparadigm',
        year: 2015,
        position: 7,
        persantage: 5,
    },
    {
        name: 'Swift',
        type: 'Multiparadigm',
        year: 2024,
        position: 6,
        persantage: 10,
    },
    {
        name: 'Swift',
        type: 'Multiparadigm',
        year: 2023,
        position: 6,
        persantage: 10,
    },
    {
        name: 'Go',
        type: 'Multiparadigm',
        year: 2015,
        position: 10,
        persantage: 4,
    },
    {
        name: 'Go',
        type: 'Multiparadigm',
        year: 2024,
        position: 7,
        persantage: 7,
    },
    {
        name: 'Go',
        type: 'Multiparadigm',
        year: 2023,
        position: 7,
        persantage: 7,
    },
    {
        name: 'Kotlin',
        type: 'Object-Oriented',
        year: 2015,
        position: 9,
        persantage: 3,
    },
    {
        name: 'Kotlin',
        type: 'Object-Oriented',
        year: 2024,
        position: 8,
        persantage: 5,
    },
    {
        name: 'Kotlin',
        type: 'Object-Oriented',
        year: 2023,
        position: 8,
        persantage: 5,
    },
    {
        name: 'TypeScript',
        type: 'Multiparadigm',
        year: 2015,
        position: 12,
        persantage: 2,
    },
    {
        name: 'TypeScript',
        type: 'Multiparadigm',
        year: 2024,
        position: 9,
        persantage: 4,
    },
    {
        name: 'TypeScript',
        type: 'Multiparadigm',
        year: 2023,
        position: 9,
        persantage: 4,
    },
    {
        name: 'Scala',
        type: 'Multiparadigm',
        year: 2015,
        position: 15,
        persantage: 1,
    },
    {
        name: 'Scala',
        type: 'Multiparadigm',
        year: 2024,
        position: 10,
        persantage: 2,
    },
    {
        name: 'Scala',
        type: 'Multiparadigm',
        year: 2023,
        position: 10,
        persantage: 2,
    },
];