export type ProgLang = {
    name: string;
    type: string;
    year: number;
    position: number;
    percentage: number;
};

export const proglangs: ProgLang[]  = [
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2001,
        position: 1,
        percentage: 20,
    },
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2005,
        position: 1,
        percentage: 25,
    },
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2015,
        position: 1,
        percentage: 22,
    },
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2024,
        position: 2,
        percentage: 20,
    },
    {
        name: 'Java',
        type: 'Object-oriented',
        year: 2023,
        position: 2,
        percentage: 20,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2001,
        position: 3,
        percentage: 10,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2005,
        position: 2,
        percentage: 15,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2015,
        position: 3,
        percentage: 20,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2024,
        position: 1,
        percentage: 30,
    },
    {
        name: 'Python',
        type: 'Multiparadigm',
        year: 2023,
        position: 1,
        percentage: 30,
    },
    {
        name: 'C#',
        type: 'Object-oriented',
        year: 2001,
        position: 4,
        percentage: 5,
    },
    {
        name: 'C#',
        type: 'Object-oriented',
        year: 2005,
        position: 3,
        percentage: 7,
    },
    {
        name: 'C#',
        type: 'Object-oriented',
        year: 2015,
        position: 4,
        percentage: 9,
    },
    {
        name: 'C#',
        type: 'Object-oriented',
        year: 2024,
        position: 3,
        percentage: 10,
    },
    {
        name: 'C#',
        type: 'Object-oriented',
        year: 2023,
        position: 3,
        percentage: 10,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2001,
        position: 5,
        percentage: 6,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2005,
        position: 4,
        percentage: 10,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2015,
        position: 2,
        percentage: 15,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2024,
        position: 2,
        percentage: 25,
    },
    {
        name: 'JavaScript',
        type: 'Multiparadigm',
        year: 2023,
        position: 2,
        percentage: 25,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2001,
        position: 2,
        percentage: 10,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2005,
        position: 5,
        percentage: 9,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2015,
        position: 5,
        percentage: 7,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2024,
        position: 4,
        percentage: 6,
    },
    {
        name: 'PHP',
        type: 'Scripting',
        year: 2023,
        position: 4,
        percentage: 6,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2001,
        position: 6,
        percentage: 4,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2005,
        position: 6,
        percentage: 5,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2015,
        position: 8,
        percentage: 3,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2024,
        position: 6,
        percentage: 2,
    },
    {
        name: 'Ruby',
        type: 'Multiparadigm',
        year: 2023,
        position: 6,
        percentage: 2,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2001,
        position: 3,
        percentage: 9,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2005,
        position: 2,
        percentage: 8,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2015,
        position: 5,
        percentage: 10,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2024,
        position: 5,
        percentage: 8,
    },
    {
        name: 'C++',
        type: 'Procedural',
        year: 2023,
        position: 5,
        percentage: 8,
    },
    {
        name: 'Swift',
        type: 'Multiparadigm',
        year: 2015,
        position: 7,
        percentage: 5,
    },
    {
        name: 'Swift',
        type: 'Multiparadigm',
        year: 2024,
        position: 6,
        percentage: 10,
    },
    {
        name: 'Swift',
        type: 'Multiparadigm',
        year: 2023,
        position: 6,
        percentage: 10,
    },
    {
        name: 'Go',
        type: 'Multiparadigm',
        year: 2015,
        position: 10,
        percentage: 4,
    },
    {
        name: 'Go',
        type: 'Multiparadigm',
        year: 2024,
        position: 7,
        percentage: 7,
    },
    {
        name: 'Go',
        type: 'Multiparadigm',
        year: 2023,
        position: 7,
        percentage: 7,
    },
    {
        name: 'Kotlin',
        type: 'Object-oriented',
        year: 2015,
        position: 9,
        percentage: 3,
    },
    {
        name: 'Kotlin',
        type: 'Object-oriented',
        year: 2024,
        position: 8,
        percentage: 5,
    },
    {
        name: 'Kotlin',
        type: 'Object-oriented',
        year: 2023,
        position: 8,
        percentage: 5,
    },
    {
        name: 'TypeScript',
        type: 'Multiparadigm',
        year: 2015,
        position: 12,
        percentage: 2,
    },
    {
        name: 'TypeScript',
        type: 'Multiparadigm',
        year: 2024,
        position: 9,
        percentage: 4,
    },
    {
        name: 'TypeScript',
        type: 'Multiparadigm',
        year: 2023,
        position: 9,
        percentage: 4,
    },
    {
        name: 'Scala',
        type: 'Multiparadigm',
        year: 2015,
        position: 15,
        percentage: 1,
    },
    {
        name: 'Scala',
        type: 'Multiparadigm',
        year: 2024,
        position: 10,
        percentage: 2,
    },
    {
        name: 'Scala',
        type: 'Multiparadigm',
        year: 2023,
        position: 10,
        percentage: 2,
    },
];
